bcmdhd: add missing linux/sched/clock.h include
These included above header by accident via linux/skbuff.h
which itself was cleaned up for the 6.3-rc1 kernel and we
get compilation failures like
    .../kernel.mainline/common/../private/google-modules/wlan/bcmdhd4389/dhd_log_dump.c:2286:22: error: call to undeclared function 'local_clock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            sec_hdr.timestamp = local_clock();
                                ^
See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2870c4d6a5e4
and https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ac849f2c492

Bug: 273298779
Test: build and boot
Change-Id: Ic40da535045c63d1a42a188dab6e138f07ba12eb
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>