bcmdhd: Fix wl_[cfg80211_add_if/release_vif_macaddr] function signatures
When compiling the WLAN driver, several errors of the following nature
are emitted for wl_cfg80211_add_if() and wl_release_vif_macaddr():

wlan/bcmdhd4389/wl_android.c:13586:70: error: passing 'const unsigned
char *' to parameter of type 'u8 *' (aka 'unsigned char *') discards
qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

wdev = wl_cfg80211_add_if(cfg, primary_ndev, wl_iftype, net->name,
net->dev_addr);

wlan/bcmdhd4389/wl_cfg80211.h:3264:47: note: passing argument to
parameter 'mac' here
        wl_iftype_t wl_iftype, const char *name, u8 *mac);

Neither function should modify the MAC address parameter, so reflect
this by updating the function signatures to use const u8 pointers.

Bug: 217483442
Signed-off-by: Isaac J. Manjarres <isaacmanjarres@google.com>
Change-Id: I99cb9cf58d596509cf8efdd519316315f5d140a8
(cherry picked from commit e2a75725055a2ed2be56848667deb69856e4fb7e)